from .redteam import (
    REDTEAM_CASE_GEN_PROMPT,
    REDTEAM_CASE_GEN_PROMPT_WITH_INSTRUCTION,
    REDTEAM_CASE_GEN_SYSTEM_MESSAGE,
)
from .standard import (
    STANDARD_CASE_GEN_PROMPT,
    STANDARD_CASE_GEN_PROMPT_WITH_INSTRUCTION,
    STANDARD_CASE_GEN_SYSTEM_MESSAGE,
)
from .redteam_zh import (
    REDTEAM_CASE_GEN_PROMPT_ZH,
    REDTEAM_CASE_GEN_PROMPT_WITH_INSTRUCTION_ZH,
    REDTEAM_CASE_GEN_SYSTEM_MESSAGE_ZH,
)
from .standard_zh import (
    STANDARD_CASE_GEN_PROMPT_ZH,
    STANDARD_CASE_GEN_PROMPT_WITH_INSTRUCTION_ZH,
    STANDARD_CASE_GEN_SYSTEM_MESSAGE_ZH,
)