from .adversarial import (
    ADV_SIMULATOR_CRITIQUE,
    ADV_SIMULATOR_CRITIQUE_REPEAT,
    ADV_SIMULATOR_PROMPT,
    ADV_SIMULATOR_SYSTEM_INFO,
)
from .standard import (
    STD_SIMULATOR_CRITIQUE,
    STD_SIMULATOR_CRITIQUE_REPEAT,
    STD_SIMULATOR_PROMPT,
    STD_SIMULATOR_SYSTEM_INFO,
)
from .adversarial_zh import (
    ADV_SIMULATOR_CRITIQUE_ZH,
    ADV_SIMULATOR_CRITIQUE_REPEAT_ZH,
    ADV_SIMULATOR_PROMPT_ZH,
    ADV_SIMULATOR_SYSTEM_INFO_ZH,
)
from .standard_zh import (
    STD_SIMULATOR_CRITIQUE_ZH,
    STD_SIMULATOR_CRITIQUE_REPEAT_ZH,
    STD_SIMULATOR_PROMPT_ZH,
    STD_SIMULATOR_SYSTEM_INFO_ZH,
)